### ISSUE TITLE
Definir hospedagem do servidor do jogo

### ISSUE THREAD

**Issue by Gabjomar** [gabgilds/Soccer-Simulator#26]
Definir forma e local de hospedagem do servidor de jogo para que os clientes possam de conectar:

GCP?
AWS?
Azure?
Heroku?
(Outro)?
Impactado por https://github.com/boidacarapreta/adcipt20221/issues/26.

**Comment by igorgilds** [comment]
Estático - Github Pages
Dinâmico - Heroku
