### ISSUE TITLE
Definir URLs/endpoints para conexão com o servidor do jogo

### ISSUE THREAD

**Issue by Gabjomar** [gabgilds/Soccer-Simulator#27]
Definir o nome do servidor, bem como os recursos ou endpoints disponíveis para conexão entre clientes/jogadores e servidor do jogo. Depende de https://github.com/boidacarapreta/adcipt20221/issues/27.

**Comment by igorgilds** [comment]
soccermanager.ifsc.cloud - Pessoa escrever na URL
servidorsoccermanager.ifsc.cloud - Servidor
