### ISSUE TITLE
Cronômetro do Jogo acelerando quando clica em jogar novamente.

### ISSUE THREAD

**Issue by Gabjomar** [gabgilds/Soccer-Simulator#31]
O código do cronômetro está presente a partir da linha 251 da cena1.js. Commit com esse problema: 8b0d78d0c8c8d2828ef7f3169afa913cb4c7ba54

**Comment by ghost** [comment]
Ao que parece, a cada rodada é criado um novo evento de tempo (`time.addEvent`), o que significa que haverá dois contadores de tempo, duplicando a contagem (e reduzindo o tempo pela metade). Uma sugestão de solução é, a cada nova rodada (`if (contadorPartidas > 0)`), remover o contador anterior (`time.removeEvent(passagemTempo)`), por volta da linha 241:

```js
  //iniciando o cronometro
  //define o tempo inicial
  tempoInicial = 0;
  if (contadorPartidas > 0) {
    time.removeEvent(passagemTempo);
  }
  passagemTempo = time.addEvent({
    callback: () => {
      tempoInicial += 15; //A cada 100 ms tira 15 segundos do tempo inicial
      cronometro.setText(formatarTempo(tempoInicial));
    },
    callbackScope: this,
    delay: 100,
    loop: true,
  });
```

**Comment by igorgilds** [comment]
O problema aparentemente era esse mesmo. A solução proposta deu certo.
