### ISSUE TITLE
Publicar a versão v1.1 para dispositivos móveis #44

### ISSUE THREAD

**Issue by igorgilds** [gabgilds/Soccer-Simulator#50]
Depende de https://github.com/boidacarapreta/adcipt20221/issues/41, https://github.com/boidacarapreta/adcipt20221/issues/42 e https://github.com/boidacarapreta/adcipt20221/issues/43.

**Comment by Gabjomar** [comment]
Commit da V1.1 do jogo: 3437ab0c0168e5ffc98b0cc0ecb000acfcba2090

**Comment by Gabjomar** [comment]
Commit da V1.2 do jogo: 849b957a30af6a3ffcae2ec454a0eefc09bb7cc1
