### ISSUE TITLE
Erro sicronização de clubes de um jogador para o outro

### ISSUE THREAD

**Issue by igorgilds** [gabgilds/Soccer-Simulator#53]
Commit com o erro: e44acdce8eb46d6f02b824dda42520bb10e8f54a

**Comment by ghost** [comment]
Houve mudança de escopo, e por isso `this.socket` nem existe. Como a linha 738 contorna isso:

```js
  var socket = this.socket;
```

então pode usar apenas `socket` ao invés de `this.socket`.

**Comment by igorgilds** [comment]
Realmente era um erro de escopo. Solução proposta funcionou.
